server.port=8090

# Spring
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Acquiring Bank
bank.simulator.base.url=http://localhost:8080

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.diskspace.enabled=false
management.health.ping.enabled=false

# Logging
logging.file.name=logs/payment-gateway.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.file-name-pattern=logs/payment-gateway.%d{yyyy-MM-dd}.%i.log.gz